baseURL: https://pcpg.github.io/portfolio/
disablePathToLower: true
languageCode: ja
title: portfolio, ivain 2019
publishDir: docs
canonifyurls: true
theme: lanyon-hugo
params:
  AuthorName: ivain
  GitHubUser: pcpg
  SidebarRecentLimit: 5
  tagline: version 2019.06
  title: The portfolio of ivain
